ip : 127.0.0.1

server:
  port: 8080
  context-path: /

web:
  upload-path : /home/caogen/project/blog/blogImg/
  load-path : /home/caogen/project/blog
  blogImg-path : /blogImg/

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${ip}:3306/caogenBlog?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: caogen
  thymeleaf:
    mode: HTML
    cache: false
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.load-path}
  http:
    multipart:
      max-file-size: 5MB
      max-request-size: 100MB
  data:
    solr:
      host: http://${ip}:8983/solr/caogen_core

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.caogen.blog.entity

jedis :
  pool :
    host : ${ip}
    port : 6379
    password : caogen
    timeout : 60000
    config :
      maxTotal: 100
      maxIdle: 10
      maxWaitMillis : 100000

qiniuyun :
  AK : 8X3xhJJ0f68vsOgKYFDDEQcM8SrZtYAnxAjkhx_T
  SK : 49QhcLK_ur1yqOOrJlir1vitcTkG6eghScSR1EnA
  bucket : blog
  url : https://cdn.kcaogen.com/

security:
  user:
    name: admin
    password: admin

logging:
  path: /home/caogen/project/blog/logs/

